# Input Normalisation
### Fraud Detection System Development using Deep Neural Network for Reported Transactional Data in DANA

#### Import Libraries

In [59]:
import pandas as pd
import numpy as np
from datetime import date

#### Load CSV File

In [10]:
df = pd.read_csv("user_data_test.csv",  sep=';')

In [11]:
df.head()

,Unnamed: 0,uid,is_scammer,source,trx_date,report_date,registereddate,birthday,gender,job_position,...,dormancy_count_trx,kyc_total_failed,kyc_total_revoked,avg_topup_weight_1,avg_x2x_weight_1,avg_other_weight_1,centrality_outdegree_p2p,centrality_indegree_p2p,centrality_undirected_p2p,centrality_outdegree_sendmoney
0,21796,b3007010-e28e-4b0a-8549-a9dfd7f58ff3,0,INCOMPLETE_CS_REPORT_VICTIM,11/03/2023,11/03/2023,01/09/2022,01/08/1999,Male,PELAJAR / MAHASISWA,...,100,0.0,0.0,49010417,175,18802083,1.413487e+08,7.067437e+07,2.120231e+08,1.306080e+09
1,271,76bef4cc-81d2-4759-80ac-8ffa6324f958,1,INCOMPLETE_CS_REPORT_SCAMMER,23/02/2023,23/02/2023,01/02/2023,01/08/1955,Female,MENGURUS RUMAH TANGGA,...,5,0.0,0.0,8333333,3333333,1666667,0.000000e+00,3.230000e+11,3.230000e+11,6.530402e+05
2,31661,4c40e720-9640-4aff-8f54-22603fed66ec,0,INCOMPLETE_CS_REPORT_VICTIM,17/02/2023,17/02/2023,01/07/2022,01/02/2003,Male,PELAJAR / MAHASISWA,...,7,0.0,0.0,3333333,3333333,0,7.067437e+07,0.000000e+00,7.067437e+07,0.000000e+00
3,9679,1b92b298-eb2e-4efd-a881-131a267182b8,0,CS_REPORT_VICTIM,22/12/2022,11/01/2023,01/11/2021,01/10/1989,Female,KARYAWAN SWASTA,...,37,0.0,0.0,14791667,30729167,57291667,2.120231e+08,1.413487e+08,3.533719e+09,1.959121e+09
4,17295,6d407ea1-8f3e-4766-a7f7-72324eba15d2,1,INCOMPLETE_CS_REPORT_SCAMMER,18/01/2023,18/01/2023,01/06/2022,01/04/1997,Male,BELUM / TIDAK BEKERJA,...,30,50.0,0.0,5416667,2375,425,7.067437e+07,7.067437e+07,7.067437e+07,3.265201e+08

#### Start Cleaning Here

In [12]:
df1 = df.copy()

In [16]:
# Drop 'uid' and 'id' columns
df1 = df.drop(columns = ['uid', 'Unnamed: 0', 'is_scammer'])
df1.head()

,source,trx_date,report_date,registereddate,birthday,gender,job_position,is_verified,aqc_freq_prepaid_mobile,aqc_mean_prepaid_mobile_amount,...,dormancy_count_trx,kyc_total_failed,kyc_total_revoked,avg_topup_weight_1,avg_x2x_weight_1,avg_other_weight_1,centrality_outdegree_p2p,centrality_indegree_p2p,centrality_undirected_p2p,centrality_outdegree_sendmoney
0,INCOMPLETE_CS_REPORT_VICTIM,11/03/2023,11/03/2023,01/09/2022,01/08/1999,Male,PELAJAR / MAHASISWA,1,0,0.000000e+00,...,100,0.0,0.0,49010417,175,18802083,1.413487e+08,7.067437e+07,2.120231e+08,1.306080e+09
1,INCOMPLETE_CS_REPORT_SCAMMER,23/02/2023,23/02/2023,01/02/2023,01/08/1955,Female,MENGURUS RUMAH TANGGA,1,0,0.000000e+00,...,5,0.0,0.0,8333333,3333333,1666667,0.000000e+00,3.230000e+11,3.230000e+11,6.530402e+05
2,INCOMPLETE_CS_REPORT_VICTIM,17/02/2023,17/02/2023,01/07/2022,01/02/2003,Male,PELAJAR / MAHASISWA,1,0,0.000000e+00,...,7,0.0,0.0,3333333,3333333,0,7.067437e+07,0.000000e+00,7.067437e+07,0.000000e+00
3,CS_REPORT_VICTIM,22/12/2022,11/01/2023,01/11/2021,01/10/1989,Female,KARYAWAN SWASTA,1,10,2.130000e+15,...,37,0.0,0.0,14791667,30729167,57291667,2.120231e+08,1.413487e+08,3.533719e+09,1.959121e+09
4,INCOMPLETE_CS_REPORT_SCAMMER,18/01/2023,18/01/2023,01/06/2022,01/04/1997,Male,BELUM / TIDAK BEKERJA,1,16,9.940000e+15,...,30,50.0,0.0,5416667,2375,425,7.067437e+07,7.067437e+07,7.067437e+07,3.265201e+08

In [31]:
# Fill NULL data in column 8 - 42 (numeric data)
for i in range (8, 43):
    df1[df1.columns[i]] = df1[df1.columns[i]].fillna(0)
    
# Fill NULL data in date and time format columns
df1['trx_date'].fillna("11/01/2020") #18272
df1['report_date'].fillna("7/01/2020") #18268
df1['registereddate'].fillna("22/10/2013") #16000
df1['birthday'].fillna("7/12/1928") #-15000

In [97]:
(pd.to_datetime("7/12/1928", format="%d/%m/%Y") - np.datetime64(0, 'Y')).days

-15000

In [14]:
# Datetime-format columns change to integer
for i in range (1, 5):
    df1[df1.columns[i]] = pd.to_datetime(df1[df1.columns[i]])
    df1[df1.columns[i]] = (df1[df1.columns[i]] - np.datetime64(0, Y).dt.days)

df1['trx_date'] = pd.to_datetime(df1['trx_date'])
df1['trx_date'] = (df1['trx_date'] - np.datetime64(0, 'Y')).dt.days

df1['report_date'] = pd.to_datetime(df1['report_date'])
df1['report_date'] = (df1['report_date'] - np.datetime64(0, 'Y')).dt.days

df1['registereddate'] = pd.to_datetime(df1['registereddate'])
df1['registereddate'] = (df1['registereddate'] - np.datetime64(0, 'Y')).dt.days

df1['birthday'] = pd.to_datetime(df1['birthday'])
df1['birthday'] = (df1['birthday'] - np.datetime64(0, 'Y')).dt.days

In [ ]:
# Fill NULL data